live_config_reload = true
"window.dynamic_title" = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0xb0b0b0"
blue = "0xd0d0d0"
cyan = "0xbe643c"
green = "0x303030"
magenta = "0xf5f5f5"
red = "0xfc6d24"
white = "0xffffff"
yellow = "0x505050"

[colors.cursor]
cursor = "0xe0e0e0"
text = "0x000000"

[colors.normal]
black = "0x000000"
blue = "0x6fb3d2"
cyan = "0x76c7b7"
green = "0xa1c659"
magenta = "0xd381c3"
red = "0xfb0120"
white = "0xe0e0e0"
yellow = "0xfda331"

[colors.primary]
background = "0x3b4252"
foreground = "0xe0e0e0"

[cursor]
style = "Block"
unfocused_hollow = false

[debug]
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "JetBrainsMono"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono"
style = "Italic"

[font.normal]
family = "JetBrainsMono"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
key = "N"
mods = "Command"

[keyboard.bindings.command]
args = ["-nb", "io.alacritty"]
program = "open"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Home"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[H"
key = "Home"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "End"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[F"
key = "End"
mode = "~AppCursor"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[5;2~"
key = "PageUp"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[5;5~"
key = "PageUp"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[5~"
key = "PageUp"

[[keyboard.bindings]]
chars = "\u001B[6;2~"
key = "PageDown"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[6;5~"
key = "PageDown"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[6~"
key = "PageDown"

[[keyboard.bindings]]
chars = "\u001B[Z"
key = "Tab"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u007F"
key = "Back"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[2~"
key = "Insert"

[[keyboard.bindings]]
chars = "\u001B[3~"
key = "Delete"

[[keyboard.bindings]]
chars = "\u001B[1;2D"
key = "Left"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5D"
key = "Left"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3D"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[D"
key = "Left"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOD"
key = "Left"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1;2C"
key = "Right"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5C"
key = "Right"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3C"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[C"
key = "Right"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOC"
key = "Right"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1;2A"
key = "Up"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5A"
key = "Up"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3A"
key = "Up"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[A"
key = "Up"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOA"
key = "Up"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[1;2B"
key = "Down"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5B"
key = "Down"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;3B"
key = "Down"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[B"
key = "Down"
mode = "~AppCursor"

[[keyboard.bindings]]
chars = "\u001BOB"
key = "Down"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001BOP"
key = "F1"

[[keyboard.bindings]]
chars = "\u001BOQ"
key = "F2"

[[keyboard.bindings]]
chars = "\u001BOR"
key = "F3"

[[keyboard.bindings]]
chars = "\u001BOS"
key = "F4"

[[keyboard.bindings]]
chars = "\u001B[15~"
key = "F5"

[[keyboard.bindings]]
chars = "\u001B[17~"
key = "F6"

[[keyboard.bindings]]
chars = "\u001B[18~"
key = "F7"

[[keyboard.bindings]]
chars = "\u001B[19~"
key = "F8"

[[keyboard.bindings]]
chars = "\u001B[20~"
key = "F9"

[[keyboard.bindings]]
chars = "\u001B[21~"
key = "F10"

[[keyboard.bindings]]
chars = "\u001B[23~"
key = "F11"

[[keyboard.bindings]]
chars = "\u001B[24~"
key = "F12"

[[keyboard.bindings]]
chars = "\u001B[1;2P"
key = "F1"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;2Q"
key = "F2"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;2R"
key = "F3"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;2S"
key = "F4"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[15;2~"
key = "F5"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[17;2~"
key = "F6"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[18;2~"
key = "F7"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[19;2~"
key = "F8"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[20;2~"
key = "F9"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[21;2~"
key = "F10"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[23;2~"
key = "F11"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[24;2~"
key = "F12"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[1;5P"
key = "F1"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;5Q"
key = "F2"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;5R"
key = "F3"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;5S"
key = "F4"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[15;5~"
key = "F5"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[17;5~"
key = "F6"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[18;5~"
key = "F7"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[19;5~"
key = "F8"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[20;5~"
key = "F9"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[21;5~"
key = "F10"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[23;5~"
key = "F11"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[24;5~"
key = "F12"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;6P"
key = "F1"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;6Q"
key = "F2"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;6R"
key = "F3"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;6S"
key = "F4"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[15;6~"
key = "F5"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[17;6~"
key = "F6"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[18;6~"
key = "F7"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[19;6~"
key = "F8"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[20;6~"
key = "F9"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[21;6~"
key = "F10"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[23;6~"
key = "F11"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[24;6~"
key = "F12"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;3P"
key = "F1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[1;3Q"
key = "F2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[1;3R"
key = "F3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[1;3S"
key = "F4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[15;3~"
key = "F5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[17;3~"
key = "F6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[18;3~"
key = "F7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[19;3~"
key = "F8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[20;3~"
key = "F9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[21;3~"
key = "F10"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[23;3~"
key = "F11"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[24;3~"
key = "F12"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006v"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006s"
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0006x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006h"
key = "H"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006j"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006n"
key = "RBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0006p"
key = "LBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0006z"
key = "Return"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u00061"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00062"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00063"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00064"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00065"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00066"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00067"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00068"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00069"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006H"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006J"
key = "Down"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006K"
key = "Up"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006L"
key = "Right"
mods = "Command"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[mouse.double_click]
threshold = 300

[mouse.triple_click]
threshold = 300

[schemes.dark.bright]
black = "0x666666"
blue = "0x7aa6da"
cyan = "0x54ced6"
green = "0x9ec400"
magenta = "0xb77ee0"
red = "0xff3334"
white = "0xffffff"
yellow = "0xe7c547"

[schemes.dark.cursor]
cursor = "0xeaeaea"
text = "0x191919"

[schemes.dark.dim]
black = "0x333333'"
blue = "0x6699cc"
cyan = "0x66cccc"
green = "0x99cc99"
magenta = "0xcc99cc"
red = "0xf2777a"
white = "0xdddddd"
yellow = "0xffcc66"

[schemes.dark.normal]
black = "0x000000"
blue = "0x7aa6da"
cyan = "0x70c0ba"
green = "0xb9ca4a"
magenta = "0xc397d8"
red = "0xd54e53"
white = "0xffffff"
yellow = "0xe6c547"

[schemes.dark.primary]
background = "0x191919"
foreground = "0xeaeaea"

[schemes.light.bright]
black = "#5c6370"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#ffffff"
yellow = "#d19a66"

[schemes.light.cursor]
cursor = "0x657d83"
text = "0xfdf6e3"

[schemes.light.normal]
black = "#282c34"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#abb2bf"
yellow = "#d19a66"

[schemes.light.primary]
background = "#ffffff"
foreground = "#282c34"

[schemes.onedark.bright]
black = "#5c6370"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#ffffff"
yellow = "#d19a66"

[schemes.onedark.normal]
black = "#282c34"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#abb2bf"
yellow = "#d19a66"

[schemes.onedark.primary]
background = "#282c34"
foreground = "#abb2bf"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[shell]
args = ["--login"]
program = "/usr/bin/zsh"

[window]
decorations = "Full"
dynamic_padding = false
opacity = 0.65

[window.dimensions]
columns = 50
lines = 40

[window.padding]
x = 2
y = 2
